#!/usr/bin/env node
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir, platform } from "node:os";
import { spawnSync } from "node:child_process";

const STATE_DIR = join(homedir(), ".frontier-model-collaboration");
const STATE_FILE = join(STATE_DIR, "state.json");
const LEDGER_FILE = join(STATE_DIR, "ledger.jsonl");
const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILL_SOURCE_DIR = join(PACKAGE_ROOT, "skills", "frontier-model-collaboration");
const TARGETS_FILE = join(process.cwd(), "frontier-collab.targets.json");
const WORKSPACE_STATUS_DIR = join(process.cwd(), ".frontier-collab");
const WORKSPACE_STATUS_FILE = join(WORKSPACE_STATUS_DIR, "ACTIVE.md");
const VISIBLE_STATUS_FILE = join(process.cwd(), "FMC_ACTIVE.md");
const COACH_PANEL_FILE = join(process.cwd(), "FMC_COACH.html");

const MODEL_LANES = {
  codex: {
    bestFor: ["repo edits", "shell commands", "tests", "builds", "production checks", "final integration"],
    costSurface: "Codex usage quota",
  },
  claude: {
    bestFor: ["fresh review", "architecture critique", "prompt repair", "test matrices", "long-form reasoning"],
    costSurface: "Claude subscription or Anthropic API usage",
  },
  gemini: {
    bestFor: ["large-context review", "research synthesis", "alternate critique"],
    costSurface: "Gemini subscription or API usage",
  },
  local: {
    bestFor: ["summaries", "formatting", "simple transforms", "private draft review"],
    costSurface: "local compute",
  },
};

function activationLine({ from = "primary", to = "secondary", mode = "REVIEW_ONLY" } = {}) {
  const role = String(mode).toLowerCase().replace(/_/g, "-");
  return `FMC ACTIVE: ${from} owns repo/work surface; ${to} is ${role}.`;
}

function parseArgs(argv) {
  const [command = "help", ...rest] = argv;
  const flags = {};
  for (let i = 0; i < rest.length; i += 1) {
    const token = rest[i];
    if (!token.startsWith("--")) continue;
    const key = token.slice(2);
    const next = rest[i + 1];
    if (!next || next.startsWith("--")) {
      flags[key] = true;
    } else {
      flags[key] = next;
      i += 1;
    }
  }
  return { command, flags };
}

function ensureStateDir() {
  mkdirSync(STATE_DIR, { recursive: true });
}

function readState() {
  if (!existsSync(STATE_FILE)) return {};
  try {
    return JSON.parse(readFileSync(STATE_FILE, "utf8"));
  } catch {
    return {};
  }
}

function writeState(patch) {
  ensureStateDir();
  const state = {
    ...readState(),
    ...patch,
    updatedAt: new Date().toISOString(),
  };
  writeFileSync(STATE_FILE, `${JSON.stringify(state, null, 2)}\n`);
  writeWorkspaceStatus(state);
  return state;
}

function writeWorkspaceStatus(state) {
  mkdirSync(WORKSPACE_STATUS_DIR, { recursive: true });
  const isActive = state.mode && state.mode !== "complete";
  const activeLine = isActive
    ? `FMC ACTIVE: ${state.activeOwner || "primary"} owns repo/work surface; ${state.handoffTo || "no secondary model"} is ${String(state.outputFormat || state.mode).toLowerCase().replace(/_/g, "-")}.`
    : "FMC IDLE: No active model handoff.";
  const allowedFiles = Array.isArray(state.allowedFiles) && state.allowedFiles.length
    ? state.allowedFiles.map((file) => `- ${file}`).join("\n")
    : "- No active file boundary.";
  const cost = state.costProfile || {};
  const body = `${activeLine}

# Frontier Model Collaboration Status

- Owner: ${state.activeOwner || "none"}
- Secondary: ${state.handoffTo || "none"}
- Mode: ${state.mode || "none"}
- Output: ${state.outputFormat || "none"}
- Task: ${state.task || "none"}
- Updated: ${state.updatedAt || new Date().toISOString()}
- Routing policy: ${cost.policy || "none"}
- Recommended lane: ${cost.recommendedLane || "none"}
- Usage surface: ${cost.costSurface || "none"}

## Allowed Files

${allowedFiles}

This file is generated by FMC Switchboard so your IDE has a visible activation indicator.
`;
  writeFileSync(WORKSPACE_STATUS_FILE, body);
  writeFileSync(VISIBLE_STATUS_FILE, body);
}

function appendLedger(event) {
  ensureStateDir();
  const entry = {
    at: new Date().toISOString(),
    cwd: process.cwd(),
    ...event,
  };
  writeFileSync(LEDGER_FILE, `${JSON.stringify(entry)}\n`, { flag: "a" });
}

function arrayValue(value) {
  if (!value) return [];
  return String(value)
    .split(",")
    .map((item) => item.trim().replace(/\\/g, "/"))
    .filter(Boolean);
}

function listValue(value, fallback) {
  if (!value) return fallback;
  return String(value)
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean)
    .join("\n");
}

function gitChangedFiles() {
  const result = spawnSync("git", ["status", "--porcelain", "--untracked-files=all"], { encoding: "utf8" });
  if (result.status !== 0) return null;
  return result.stdout
    .split(/\r?\n/)
    .filter((line) => line.trim())
    .map((line) => {
      const renamed = line.match(/^R\s+(.+)\s+->\s+(.+)$/);
      if (renamed) return renamed[2].replace(/\\/g, "/");
      return line.slice(3).replace(/\\/g, "/");
    });
}

function costProfile(flags) {
  const policy = flags.policy || "balanced";
  const risk = flags.risk || "medium";
  const context = flags.context || "medium";
  const task = String(flags.task || "").toLowerCase();
  const requestedTo = flags.to ? String(flags.to).toLowerCase() : "";
  const format = String(flags.format || "").toUpperCase();
  const nonEditingOutput = ["DESIGN_SPEC", "REVIEW_ONLY", "PLAN_ONLY", "TEST_MATRIX", "PROMPT_DRAFT"].includes(format);
  const explicitNoEdit = task.match(/\b(without modifying|do not modify|no code|no edits|design proposal|design spec)\b/);

  let recommendedLane = requestedTo || "claude";
  let reason = "Secondary review gives fresh eyes while the primary operator keeps ownership.";

  if (policy === "conserve" && risk === "low") {
    recommendedLane = "local";
    reason = "Low-risk work should use local or cheaper lanes before spending frontier usage.";
  } else if (nonEditingOutput || explicitNoEdit) {
    recommendedLane = requestedTo || "claude";
    reason = "Non-editing specs, reviews, and plans are safe high-leverage secondary-model work.";
  } else if (task.match(/\b(deploy|restart|production|ssh|build|test|fix|edit|patch)\b/)) {
    recommendedLane = "codex";
    reason = "Repo-changing or production-sensitive work should stay with the primary operator.";
  } else if (task.match(/\b(review|critique|prompt|architecture|test matrix|risk|ux)\b/)) {
    recommendedLane = requestedTo || "claude";
    reason = "Review, critique, prompts, and test design are high-leverage secondary-model tasks.";
  } else if (context === "large" && policy !== "conserve") {
    recommendedLane = requestedTo || "gemini";
    reason = "Large-context work may benefit from a large-context review lane if available.";
  }

  const lane = MODEL_LANES[recommendedLane] || MODEL_LANES.claude;
  return {
    policy,
    risk,
    context,
    recommendedLane,
    reason,
    costSurface: lane.costSurface,
    bestFor: lane.bestFor,
  };
}

function createPacket(flags) {
  const from = flags.from || "codex";
  const to = flags.to || "review-model";
  const task = flags.task || "Review the current work and return bounded feedback.";
  const role = flags.role || `${to} is the secondary model. ${from} remains the primary operator.`;
  const allowed = listValue(flags.files, "[list exact files, diff, or context]");
  const readOnly = listValue(flags["read-only"] || flags.readonly, "All files unless explicitly owned.");
  const format = flags.format || "REVIEW_ONLY";
  const budget = flags.budget || "One concise pass. Prioritize high-impact issues.";
  const limits = flags.limits || "No production actions unless explicitly approved.";
  const cost = costProfile(flags);

  return `${activationLine({ from, to, mode: format })}

TASK:
${task}

ROLE:
${role}

DO:
${flags.do || "- Stay within the assigned role.\n- Return only the requested output.\n- State any assumptions or missing context."}

DO NOT:
${flags["do-not"] || "- Edit files unless explicitly allowed.\n- Run deploys or restarts.\n- Ask for or reveal secrets.\n- Redesign unrelated systems."}

FILES ALLOWED:
${allowed}

FILES READ-ONLY:
${readOnly}

PRODUCTION LIMITS:
${limits}

OUTPUT FORMAT:
${format}

TIME/USAGE BUDGET:
${budget}

COST / ROUTING FACTORS:
Policy: ${cost.policy}
Risk: ${cost.risk}
Context size: ${cost.context}
Recommended lane: ${cost.recommendedLane}
Why: ${cost.reason}
Usage surface: ${cost.costSurface}
`;
}

function copyToClipboard(text) {
  const sys = platform();
  if (sys === "win32") {
    const result = spawnSync("clip.exe", { input: text, encoding: "utf8" });
    return result.status === 0;
  }
  if (sys === "darwin") {
    const result = spawnSync("pbcopy", { input: text, encoding: "utf8" });
    return result.status === 0;
  }
  for (const command of ["wl-copy", "xclip", "xsel"]) {
    const result = spawnSync(command, command === "xclip" ? ["-selection", "clipboard"] : [], {
      input: text,
      encoding: "utf8",
    });
    if (result.status === 0) return true;
  }
  return false;
}

function notify(title, message) {
  const sys = platform();
  if (sys === "win32") {
    const script = `
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$n = New-Object System.Windows.Forms.NotifyIcon
$n.Icon = [System.Drawing.SystemIcons]::Information
$n.Visible = $true
$n.ShowBalloonTip(4000, ${psQuote(title)}, ${psQuote(message)}, [System.Windows.Forms.ToolTipIcon]::Info)
Start-Sleep -Seconds 5
$n.Dispose()
`;
    spawnSync("powershell.exe", ["-NoProfile", "-STA", "-Command", script], { stdio: "ignore" });
    return;
  }
  if (sys === "darwin") {
    spawnSync("osascript", ["-e", `display notification ${jsonQuote(message)} with title ${jsonQuote(title)}`], {
      stdio: "ignore",
    });
    return;
  }
  spawnSync("notify-send", [title, message], { stdio: "ignore" });
}

function psQuote(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function jsonQuote(value) {
  return JSON.stringify(String(value));
}

function openTarget(name) {
  if (!existsSync(TARGETS_FILE)) {
    console.error(`No ${TARGETS_FILE} found. Copy examples/frontier-collab.targets.example.json first.`);
    return false;
  }
  const targets = JSON.parse(readFileSync(TARGETS_FILE, "utf8"));
  const target = targets[name];
  if (!target || !target.command) {
    console.error(`Target "${name}" is not configured.`);
    return false;
  }
  const args = Array.isArray(target.args) ? target.args : [];
  const result = spawnSync(target.command, args, { stdio: "ignore", shell: Boolean(target.shell) });
  return result.status === 0;
}

function openFile(filePath) {
  const sys = platform();
  if (sys === "win32") {
    spawnSync("cmd", ["/c", "start", "", filePath], { stdio: "ignore" });
    return;
  }
  if (sys === "darwin") {
    spawnSync("open", [filePath], { stdio: "ignore" });
    return;
  }
  spawnSync("xdg-open", [filePath], { stdio: "ignore" });
}

function defaultSkillDest() {
  const codexHome = process.env.CODEX_HOME || join(homedir(), ".codex");
  return join(codexHome, "skills", "frontier-model-collaboration");
}

function installSkill(flags) {
  const dest = flags.dest || defaultSkillDest();
  const destExists = existsSync(join(dest, "SKILL.md"));
  if (destExists && !flags.force) {
    return {
      ok: true,
      installed: true,
      changed: false,
      skillPath: dest,
      message: "Skill already installed. Use --force to overwrite it with this package copy.",
    };
  }
  mkdirSync(dirname(dest), { recursive: true });
  cpSync(SKILL_SOURCE_DIR, dest, { recursive: true, force: true });
  return {
    ok: true,
    installed: true,
    changed: true,
    skillPath: dest,
    message: "Skill installed. Restart Codex or open a new agent session so the skill registry refreshes.",
  };
}

function doctor(flags) {
  const dest = flags.dest || defaultSkillDest();
  const checks = [
    { name: "package skill exists", ok: existsSync(join(SKILL_SOURCE_DIR, "SKILL.md")) },
    { name: "package metadata exists", ok: existsSync(join(SKILL_SOURCE_DIR, "agents", "openai.yaml")) },
    { name: "installed skill exists", ok: existsSync(join(dest, "SKILL.md")), path: dest },
    { name: "workspace badge exists", ok: existsSync(VISIBLE_STATUS_FILE), path: VISIBLE_STATUS_FILE },
  ];
  const ok = checks.every((check) => check.ok);
  return { ok, checks };
}

function smoke(flags) {
  const from = flags.from || "codex";
  const to = flags.to || "claude";
  const mode = flags.format || "REVIEW_ONLY";
  const state = writeState({
    activeOwner: from,
    handoffTo: to,
    mode: "handoff",
    task: flags.task || "FMC smoke test: prove the switchboard is active.",
    allowedFiles: arrayValue(flags.files || "FMC_ACTIVE.md"),
    readOnlyFiles: [],
    outputFormat: mode,
    productionLimits: "No production actions. Smoke test only.",
    costProfile: costProfile({ ...flags, from, to }),
    lastPacketPath: null,
  });
  appendLedger({ type: "smoke", from, to, outputFormat: mode });
  if (flags.notify) notify("FMC Active", `${from} owns repo; ${to} is ${mode.toLowerCase().replace(/_/g, "-")}`);
  return {
    ok: true,
    active: activationLine({ from, to, mode }),
    badge: VISIBLE_STATUS_FILE,
    state,
    next: "Open FMC_ACTIVE.md in your IDE. If the first line says FMC ACTIVE, the switchboard is working.",
  };
}

function htmlEscape(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function jsString(value) {
  return JSON.stringify(String(value ?? ""));
}

function coachPanel(flags) {
  const state = readState();
  writeWorkspaceStatus(state);
  const from = state.activeOwner || flags.from || "codex";
  const to = state.handoffTo || flags.to || "claude";
  const mode = state.outputFormat || flags.format || "REVIEW_ONLY";
  const task = state.task || flags.task || "Review this work and tell the primary operator what is risky.";
  const packet = createPacket({
    from,
    to,
    format: mode,
    task,
    files: Array.isArray(state.allowedFiles) ? state.allowedFiles.join(",") : "",
    policy: state.costProfile?.policy || flags.policy || "balanced",
    risk: state.costProfile?.risk || flags.risk || "medium",
    context: state.costProfile?.context || flags.context || "medium",
  });
  const nextStep = state.mode === "complete"
    ? "No active handoff. Press Copy Handoff when you want to send work to another model."
    : `Paste the handoff into ${to}. When ${to} stops answering, copy the answer back to the primary operator.`;
  const body = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>FMC Coach</title>
  <style>
    :root { color-scheme: dark; --bg:#07090d; --panel:#111722; --panel2:#172231; --line:#294258; --text:#eff7ff; --muted:#9db0c3; --accent:#7ee3f5; --ok:#8ae6a8; --warn:#ffcf70; --danger:#ff7d7d; }
    * { box-sizing: border-box; }
    body { margin:0; min-height:100vh; background: radial-gradient(circle at 15% 10%, rgba(126,227,245,.16), transparent 32%), linear-gradient(135deg, #07090d, #0b1119 55%, #090d13); color:var(--text); font-family: Inter, Segoe UI, system-ui, sans-serif; letter-spacing:0; }
    .wrap { width:min(1120px, 100%); margin:0 auto; padding:24px; }
    .signal { display:flex; align-items:center; gap:12px; color:var(--ok); font-weight:800; font-size:clamp(22px, 4vw, 44px); line-height:1.05; margin:0 0 18px; }
    .dot { width:18px; height:18px; border-radius:50%; background:var(--ok); box-shadow:0 0 28px var(--ok); animation:pulse 1.4s infinite; flex:0 0 auto; }
    @keyframes pulse { 0%,100%{opacity:.45; transform:scale(.8)} 50%{opacity:1; transform:scale(1.15)} }
    .grid { display:grid; grid-template-columns: 1.1fr .9fr; gap:16px; }
    .card { border:1px solid var(--line); background:linear-gradient(180deg, rgba(17,23,34,.96), rgba(13,18,28,.96)); border-radius:8px; padding:18px; box-shadow:0 18px 60px rgba(0,0,0,.35); }
    h1,h2,p { margin-top:0; }
    h2 { font-size:18px; color:var(--accent); text-transform:uppercase; letter-spacing:.08em; }
    .status { display:grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap:10px; }
    .pill { border:1px solid var(--line); background:var(--panel2); border-radius:8px; padding:12px; min-height:70px; }
    .label { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.08em; }
    .value { font-size:22px; font-weight:800; margin-top:4px; overflow-wrap:anywhere; }
    .next { font-size:24px; line-height:1.25; color:var(--text); }
    .buttons { display:grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap:12px; margin-top:16px; }
    button, a.button { min-height:64px; border:1px solid var(--line); border-radius:8px; background:#10283a; color:var(--text); font-size:18px; font-weight:800; cursor:pointer; display:flex; align-items:center; justify-content:center; text-decoration:none; text-align:center; padding:10px; }
    button:hover, a.button:hover { border-color:var(--accent); box-shadow:0 0 0 3px rgba(126,227,245,.12); }
    .primary { background:#12485c; }
    .warn { background:#3b2b10; }
    .danger { background:#3a1414; }
    textarea { width:100%; min-height:260px; resize:vertical; border:1px solid var(--line); border-radius:8px; background:#071019; color:var(--text); padding:14px; font:14px/1.45 Consolas, monospace; }
    .small { color:var(--muted); font-size:14px; }
    .toast { position:fixed; right:18px; bottom:18px; background:#10283a; border:1px solid var(--accent); padding:14px 18px; border-radius:8px; color:var(--text); display:none; box-shadow:0 12px 36px rgba(0,0,0,.45); }
    @media (max-width: 860px) { .grid, .status, .buttons { grid-template-columns:1fr; } .wrap { padding:14px; } }
    @media (prefers-reduced-motion: reduce) { .dot { animation:none; } }
  </style>
</head>
<body>
  <main class="wrap">
    <div class="signal"><span class="dot"></span><span>${htmlEscape(activationLine({ from, to, mode }))}</span></div>
    <section class="grid">
      <div class="card">
        <h2>Next Step</h2>
        <p class="next">${htmlEscape(nextStep)}</p>
        <div class="buttons">
          <button class="primary" onclick="copyPacket()">Copy Handoff</button>
          <a class="button" href="https://claude.ai" target="_blank" rel="noreferrer">Open Claude</a>
          <a class="button" href="https://chatgpt.com" target="_blank" rel="noreferrer">Open ChatGPT</a>
          <button class="warn" onclick="copyHandback()">Copy Handback Phrase</button>
        </div>
        <p class="small">This panel is local. It does not call any AI model by itself and does not send your files anywhere.</p>
      </div>
      <div class="card">
        <h2>Current Owner</h2>
        <div class="status">
          <div class="pill"><div class="label">Primary</div><div class="value">${htmlEscape(from)}</div></div>
          <div class="pill"><div class="label">Secondary</div><div class="value">${htmlEscape(to)}</div></div>
          <div class="pill"><div class="label">Mode</div><div class="value">${htmlEscape(mode)}</div></div>
          <div class="pill"><div class="label">Lane</div><div class="value">${htmlEscape(state.costProfile?.recommendedLane || to)}</div></div>
        </div>
      </div>
    </section>
    <section class="card" style="margin-top:16px">
      <h2>Clipboard Packet</h2>
      <textarea id="packet" spellcheck="false">${htmlEscape(packet)}</textarea>
    </section>
  </main>
  <div id="toast" class="toast"></div>
  <script>
    const packet = ${jsString(packet)};
    function show(message) {
      const el = document.getElementById('toast');
      el.textContent = message;
      el.style.display = 'block';
      setTimeout(() => el.style.display = 'none', 2500);
    }
    async function copyText(text, message) {
      try {
        await navigator.clipboard.writeText(text);
        show(message);
      } catch {
        document.getElementById('packet').select();
        show('Select text shown; press Ctrl+C.');
      }
    }
    function copyPacket() { copyText(packet, 'Handoff copied. Paste into ${htmlEscape(to)}.'); }
    function copyHandback() { copyText('FMC handback from ${htmlEscape(to)}: ', 'Handback phrase copied. Paste into primary chat.'); }
  </script>
</body>
</html>`;
  writeFileSync(COACH_PANEL_FILE, body);
  return COACH_PANEL_FILE;
}

function printHelp() {
  console.log(`Frontier Model Collaboration Switchboard

Usage:
  fmc install-skill
  fmc smoke
  fmc doctor
  fmc coach --open
  fmc copy --to claude --task "Review this bug"
  fmc handoff --from codex --to claude --task "Review this diff" --files "app/a.js,lib/b.js" --copy --notify
  fmc recommend --task "Review agent prompt transfer behavior" --risk high --context medium --policy balanced
  fmc state --owner codex --mode implementation --task "Fix transfer latency"
  fmc status
  fmc badge
  fmc check
  fmc complete

Options:
  --copy             Copy handoff packet to clipboard.
  --notify           Show a desktop nudge where supported.
  --open-target NAME Open a locally configured target from frontier-collab.targets.json.
  --policy NAME      Cost policy: conserve, balanced, max-quality.
  --risk NAME        Task risk: low, medium, high.
  --context NAME     Context size: small, medium, large.
  --dest PATH        Skill install destination.
  --force            Overwrite an existing installed skill.
`);
}

const { command, flags } = parseArgs(process.argv.slice(2));

if (command === "handoff" || command === "copy" || command === "copy-handoff" || command === "voice-copy") {
  const voiceFriendlyCopy = command !== "handoff";
  if (voiceFriendlyCopy) flags.copy = true;
  const packet = createPacket(flags);
  const to = flags.to || "review-model";
  const from = flags.from || "codex";
  const mode = flags.format || "REVIEW_ONLY";
  writeState({
    activeOwner: from,
    handoffTo: to,
    mode: "handoff",
    task: flags.task || "Review handoff",
    allowedFiles: arrayValue(flags.files),
    readOnlyFiles: arrayValue(flags["read-only"] || flags.readonly),
    outputFormat: mode,
    productionLimits: flags.limits || "No production actions unless explicitly approved.",
    costProfile: costProfile(flags),
    lastPacketPath: null,
  });
  appendLedger({
    type: "handoff",
    from,
    to,
    task: flags.task || "Review handoff",
    outputFormat: mode,
    allowedFiles: arrayValue(flags.files),
    costProfile: costProfile(flags),
  });
  const copied = flags.copy ? copyToClipboard(packet) : false;
  if (voiceFriendlyCopy) {
    console.log(`${activationLine({ from, to, mode })}
${copied ? "Copied handoff packet to clipboard." : "Clipboard copy was not available."}
Badge file: ${VISIBLE_STATUS_FILE}
Next: paste into ${to}.`);
  } else {
    console.log(packet);
  }
  if (flags.copy && !voiceFriendlyCopy) {
    console.error(copied ? "Copied handoff packet to clipboard." : "Clipboard copy was not available.");
  }
  if (flags.notify) {
    notify("Frontier Model Handoff", `Switching from ${from} to ${to}`);
  }
  if (flags["open-target"]) {
    openTarget(flags["open-target"]);
  }
} else if (command === "state") {
  const state = writeState({
    activeOwner: flags.owner || flags.model || "primary",
    mode: flags.mode || "working",
    task: flags.task || "",
  });
  appendLedger({ type: "state", activeOwner: state.activeOwner, mode: state.mode, task: state.task });
  console.error(`FMC ACTIVE: ${state.activeOwner} owns current ${state.mode} work.`);
  console.log(JSON.stringify(state, null, 2));
  if (flags.notify) {
    notify("Frontier Model State", `${state.activeOwner}: ${state.mode}`);
  }
} else if (command === "status") {
  const state = readState();
  if (!Object.keys(state).length) {
    console.log("No active frontier model collaboration state.");
  } else {
    console.log(JSON.stringify(state, null, 2));
  }
} else if (command === "badge") {
  const state = readState();
  writeWorkspaceStatus(state);
  console.log(VISIBLE_STATUS_FILE);
} else if (command === "install-skill") {
  const result = installSkill(flags);
  console.log(`${result.changed ? "FMC INSTALL OK" : "FMC ALREADY INSTALLED"}
Skill path: ${result.skillPath}
${result.message}

Next:
1. Restart Codex or open a new agent session.
2. Run: fmc smoke
3. Open: FMC_ACTIVE.md`);
} else if (command === "doctor") {
  const result = doctor(flags);
  console.log(JSON.stringify(result, null, 2));
  if (!result.ok) process.exitCode = 1;
} else if (command === "coach" || command === "panel") {
  const file = coachPanel(flags);
  if (flags.open) openFile(file);
  console.log(`FMC coach panel ready: ${file}
Open it in a browser, or run with --open.`);
} else if (command === "smoke") {
  const result = smoke(flags);
  console.log(`${result.active}

Smoke test passed.
Badge file: ${result.badge}

${result.next}`);
} else if (command === "recommend") {
  const cost = costProfile(flags);
  console.log(JSON.stringify({
    task: flags.task || "",
    policy: cost.policy,
    risk: cost.risk,
    context: cost.context,
    recommendedLane: cost.recommendedLane,
    usageSurface: cost.costSurface,
    bestFor: cost.bestFor,
    reason: cost.reason,
  }, null, 2));
} else if (command === "check") {
  const state = readState();
  const changed = gitChangedFiles();
  if (!changed) {
    console.error("Could not read git status. Run fmc check inside a git repository.");
    process.exitCode = 2;
  } else {
    const allowed = Array.isArray(state.allowedFiles) ? state.allowedFiles : [];
    const outside = allowed.length
      ? changed.filter((file) => !allowed.some((allowedFile) => file === allowedFile || file.startsWith(`${allowedFile}/`)))
      : [];
    const report = {
      activeOwner: state.activeOwner || null,
      handoffTo: state.handoffTo || null,
      mode: state.mode || null,
      outputFormat: state.outputFormat || null,
      changedFiles: changed,
      allowedFiles: allowed,
      outsideBoundary: outside,
      ok: allowed.length ? outside.length === 0 : true,
      warning: allowed.length ? null : "No allowedFiles boundary is active. Create a handoff with --files to enable drift checks.",
    };
    appendLedger({ type: "check", ok: report.ok, outsideBoundary: outside });
    console.log(JSON.stringify(report, null, 2));
    if (outside.length) process.exitCode = 1;
  }
} else if (command === "complete") {
  const state = writeState({ activeOwner: null, handoffTo: null, mode: "complete", task: "" });
  appendLedger({ type: "complete" });
  console.log(JSON.stringify(state, null, 2));
  if (flags.notify) {
    notify("Frontier Model Collaboration", "Work marked complete");
  }
} else {
  printHelp();
}
